version: '3.8'

services:
  web:
    build:
      target: deps
      args:
        NODE_ENV: development
    restart: no
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./web:/app

  cms:
    build:
      target: deps
      args:
        NODE_ENV: development
    restart: no
    command: npm run develop
    volumes:
      - ./cms:/app

  mysql:
    restart: no
