version: '3.8'

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    network_mode: host
    restart: always

  certbot:
    image: certbot/certbot:v1.27.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  web:
    build:
      args:
        NODE_ENV: production
    restart: always

  cms:
    build:
      args:
        NODE_ENV: production
    restart: always

  mysql:
    restart: always
