import type { NextPage } from 'next';
import Head from 'next/head';
import Post from '../interfaces/post';
import { getAllPosts } from '../lib/api/posts';

type Props = {
  allPosts: Post[];
};

const Home: NextPage<Props> = ({ allPosts }: Props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {allPosts.map((post) => (
          <div key={post.name}>{post.title}</div>
        ))}
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const allPosts = getAllPosts();

  return {
    props: { allPosts },
  };
};

export default Home;
